variable "vpc-name" {}
variable "igw-name" {}
variable "rt-name" {}
variable "subnet-name" {}
variable "sg-name" {}
variable "instance-name" {}
variable "key-name" {}
variable "iam-role" {}
variable "instance-type" {}
variable "ami" {}
variable "cidr-block" {}
variable "vpc-cidr" {}
variable "vpc-cidr-block" {}
variable "pub-sub-cidr" {}
variable "az" {}
variable "region" {}
variable "access_key" {}
variable "secret_key" {}